deploy:
  artifact: bia-versao.zip
branch-defaults:
  main:
    environment: bia-dev-v2
  dev:
    environment: bia-dev-v2
environment-defaults:
  bia-dev:
    branch: null
    repository: null
global:
  application_name: bia-app-v2
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
